[package]
name = "libphilologus"
version = "2.0.29"
authors = ["Jeremy March <jmarch@gradcenter.cuny.edu>"]
edition = "2024"

[lib]
name = "libphilologus"
path = "src/lib.rs"
doctest = false

[dependencies]

unicode-normalization = { version = "0.1.25", default-features = false }
chrono = "0.4.43"
sqlx = { version = "0.8.6", features = [
    "sqlite",
    "runtime-tokio-rustls",
    "any",
    "macros",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
regex = "1.12.3"
thiserror = "2.0.18"
tantivy = "0.22.0" #0.21.1
# polytonic-greek = { git = "https://github.com/jeremymarch/polytonic-greek", version = "0.4.6" }
hoplite_verbs_rs = { git = "https://github.com/jeremymarch/hoplite_verbs_rs", version = "0.5.1" }
# hoplite_verbs_rs = { path = "../hoplite_verbs_rs" }
tracing = { version = "0.1.44", features = ["log"] }
tracing-appender = "0.2.4"
tracing-subscriber = "0.3.22"

[dev-dependencies]
urlencoding = "2.1.3"
